### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [bugnano/rrr#1]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.2.0. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary rnr -w /tmp/ext rnr==0.2.0
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting rnr==0.2.0
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/9f7/52f0482e2e3c2/rnr-0.2.0.tar.gz (35 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-s0p86dsi/rnr/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-s0p86dsi/rnr/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-s0p86dsi/rnr/pip-egg-info
         cwd: /tmp/pip-wheel-s0p86dsi/rnr/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-s0p86dsi/rnr/setup.py", line 10, in <module>
        with open('requirements.txt', 'r') as fh:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by bugnano** [comment]
Thank you for reporting this bug, I will look into it.
In the meantime, you can use the prebuilt wheel files from PyPI
